# Generated by Django 6.0.2 on 2026-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('wireguard_ip', models.GenericIPAddressField(unique=True)),
                ('public_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
