# Generated by Django 6.0.2 on 2026-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='container',
            name='wireguard_ip',
        ),
        migrations.AddField(
            model_name='container',
            name='tailscale_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
