server_url: http://0.0.0.0:8080

listen_addr: 0.0.0.0:8080

private_key_path: /var/lib/headscale/private.key

ip_prefixes:
  - 100.64.0.0/10

dns_config:
  magic_dns: true
  base_domain: headscale.local

log_level: info